// Welcome to DAX query view! Learn more about DAX queries at https://aka.ms/dax-queries.
// Right-click on tables, columns, or measures in the data pane to access quick queries, or ask Copilot for help writing DAX.

// Select "Run" to try this sample DAX query.

/*
EVALUATE
    ADDCOLUMNS (
        VALUES ( 'Product'[ProductKey] ),
        "LastDate", CALCULATE ( MAX ( 'Inventory'[DateKey] ) ,
		TREATAS(VALUES ( 'Product'[ProductKey] ), 'Inventory'[ProductKey])
    ))
	*/
	
EVALUATE 
ADDCOLUMNS(
SUMMARIZE('Inventory','Inventory'[ProductKey]),
"DateKeyMax", CALCULATE(MAX('Inventory'[DateKey])))